package com.jxkj.fit_5a.conpoment.utils;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PathMeasure;
import android.graphics.RectF;
import android.util.Log;

import com.jxkj.fit_5a.R;
import com.jxkj.fit_5a.app.MainApplication;
import com.jxkj.fit_5a.entity.MapDetailsBean;

import java.util.ArrayList;
import java.util.List;


/**
 * Created by AuthorName on Mar 23, 2021.
 * Copyright  2021 CompanyName. All rights reserved.
 * <p>
 * Generated by PaintCode
 * http://www.paintcodeapp.com
 *
 * @author AuthorName
 */
public class StyleKitName {


    public static PathMeasure mPathMeasure;
    public static float[] mCurrentPosition;
    public static List<float[]> mCurrentPosition_box = new ArrayList<>();

    private static class CacheFor_1100900Canvas {
        private static Paint paint = new Paint();
        private static Path _2Path = new Path();
        private static Path _3Path = new Path();
    }

    public interface StyleKitInterface{
        void getLeftTop(float x,float y);

    }

    public static void draw_1100900Canvas(Canvas canvas, List<Float[]> info, MapDetailsBean.ParamBean param,
                                          Bitmap bitmap,List<MapDetailsBean.BoxsBean> box,Bitmap mBoxBit,Bitmap mBoxBit_G,StyleKitInterface mStyleKitInterface) {
        float bl =  param.getReferenceWidth()/param.getReferenceHeight();//1.5
//        Log.w("--->>>>>", "屏幕宽:" + canvas.getWidth());//1920 1852*700 900*600
//        Log.w("--->>>>>", "屏幕高:" + canvas.getHeight());//1080
        //1080*1.5
        float yBl = canvas.getHeight()/param.getHeight();
        float xBl = (canvas.getHeight() * bl)/(param.getHeight()*bl);
        //矩形范围宽:1620   150
        float rectLeft = (canvas.getWidth() - canvas.getHeight() * bl) / 2;
        float rectRight = rectLeft + canvas.getHeight() * bl;
        CacheFor_1100900Canvas._2Path.reset();
        CacheFor_1100900Canvas._2Path.moveTo(info.get(0)[0]*xBl+rectLeft, info.get(0)[1]*yBl);
        for (int i = 0; i < info.size(); i++) {
            CacheFor_1100900Canvas._2Path.lineTo(info.get(i)[0]*xBl+rectLeft, info.get(i)[1]*yBl);
        }
        CacheFor_1100900Canvas._2Path.lineTo(info.get(0)[0]*xBl+rectLeft , info.get(0)[1]*yBl);
        CacheFor_1100900Canvas.paint.reset();
        CacheFor_1100900Canvas.paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        CacheFor_1100900Canvas.paint.setStrokeWidth(5f);
        canvas.save();
        CacheFor_1100900Canvas.paint.setStyle(Paint.Style.STROKE);
        CacheFor_1100900Canvas.paint.setColor(MainApplication.getContext().getResources().getColor(R.color.transparent));
        canvas.drawPath(CacheFor_1100900Canvas._2Path, CacheFor_1100900Canvas.paint);

        for(int i=0;i<box.size();i++){
            if(mCurrentPosition_box.size() <= box.size()){
                float[] f = new float[2];
                f[0] = info.get(0)[0] * xBl + rectLeft;
                f[1] = info.get(0)[1] * yBl;
                mCurrentPosition_box.add(f);
            }
            if(!box.get(i).getReceiveInfo().isHaving()){
                canvas.drawBitmap(mBoxBit_G,mCurrentPosition_box.get(i)[0] - 25, mCurrentPosition_box.get(i)[1] - 25, null);
            }else{
                canvas.drawBitmap(mBoxBit,mCurrentPosition_box.get(i)[0] - 25, mCurrentPosition_box.get(i)[1] - 25, null);
            }
        }

        if (mCurrentPosition == null) {
            mCurrentPosition = new float[2];
            mCurrentPosition[0] = info.get(0)[0] * xBl + rectLeft;
            mCurrentPosition[1] = info.get(0)[1] * yBl;
        }
        bitmap = StringUtil.zoomImage(bitmap, 60, 78);
        canvas.drawBitmap(bitmap, mCurrentPosition[0] - 30, mCurrentPosition[1] - 78, null);


        if (mPathMeasure == null) {
            mPathMeasure = new PathMeasure(CacheFor_1100900Canvas._2Path, true);
        }
        mStyleKitInterface.getLeftTop(mCurrentPosition[0] - 30,mCurrentPosition[1] - 78);
        canvas.restore();
    }


}